package dev.minecraftstudio.reactor.selftest;

import dev.minecraftstudio.reactor.util.ResourceSource;
import org.junit.jupiter.api.Test;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

class SelfTestTest {

    private final ResourceSource classpath = ResourceSource.classpath(getClass().getClassLoader());
    /** Stable fixtures; the files in src/main/resources are regenerated by Minecraft Studio. */
    private final ResourceSource bundled = path -> classpath.read("fixtures/" + path);

    @Test
    void fixtureAssetsPass() {
        SelfTest.Result result = new SelfTest(bundled).run();
        assertTrue(result.passed(), result.summary());
        assertEquals("SELFTEST PASSED", result.summary());
    }

    @Test
    void generatedAssetsPassWhenPresent() {
        assumeTrue(classpath.read("timelines/reactor_startup.json").isPresent()
                && classpath.read("music/reactor_calm.json").isPresent(), "studio assets not generated yet");
        SelfTest.Result result = new SelfTest(classpath).run();
        assertTrue(result.passed(), result.summary());
    }

    @Test
    void missingTimelineFails() {
        ResourceSource withoutScram = path -> path.endsWith("reactor_scram.json") ? Optional.empty() : bundled.read(path);
        SelfTest.Result result = new SelfTest(withoutScram).run();
        assertFalse(result.passed());
        assertTrue(result.summary().startsWith("SELFTEST FAILED: "));
        assertTrue(result.summary().contains("reactor_scram.json is missing"));
    }

    @Test
    void malformedSoundKeyFails() {
        ResourceSource broken = path -> path.endsWith("reactor_shutdown.json")
                ? Optional.of("{\"id\":\"reactor_shutdown\",\"cues\":[{\"tick\":0,\"track\":\"sfx\",\"sound\":\"Reactor:Bad Key\"}]}")
                : bundled.read(path);
        SelfTest.Result result = new SelfTest(broken).run();
        assertFalse(result.passed());
        assertTrue(result.summary().contains("malformed sound key 'Reactor:Bad Key'"), result.summary());
    }

    @Test
    void brokenMusicMetadataFails() {
        ResourceSource broken = path -> path.endsWith("reactor_alarm.json") ? Optional.of("{\"state\":\"alarm\"}")
                : bundled.read(path);
        SelfTest.Result result = new SelfTest(broken).run();
        assertFalse(result.passed());
        assertTrue(result.summary().contains("reactor_alarm.json"), result.summary());
    }
}
