package dev.minecraftstudio.reactor.music;

import dev.minecraftstudio.reactor.util.ResourceSource;
import org.junit.jupiter.api.Test;

import java.util.logging.Logger;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

class MusicSessionTest {

    /** Fixed fixtures (the bundled files are regenerated by Minecraft Studio and may change). */
    private final ResourceSource fixtures = path -> ResourceSource.classpath(getClass().getClassLoader())
            .read("fixtures/" + path);
    private final MusicLibrary library = MusicLibrary.load(fixtures, Logger.getAnonymousLogger());
    private final MusicMetadata calm = library.get(MusicState.CALM).orElseThrow();
    private final MusicMetadata alarm = library.get(MusicState.ALARM).orElseThrow();

    @Test
    void bundledMetadataParses() {
        assertEquals(92, calm.bpm(), 1e-9);
        assertEquals(5.217391, calm.introSeconds(), 1e-6);
        assertEquals(20.869565, calm.loopSeconds(), 1e-6);
        assertEquals(2, calm.transitionEveryBars());
        assertEquals(8, calm.loopBars());
        assertEquals(5.217391, calm.outroSeconds(), 1e-6);
        assertTrue(calm.hasOutro());
        assertFalse(alarm.hasOutro());
        assertEquals(132, alarm.bpm(), 1e-9);
        assertEquals(14.545455, alarm.loopSeconds(), 1e-6);
        assertEquals(291, Math.round(alarm.loopSeconds() * 20));
    }

    @Test
    void silentSessionSwitchesImmediately() {
        MusicSession s = new MusicSession();
        s.request(MusicState.CALM, Quantize.BAR, 40);
        assertTrue(s.switchDue(40));
        assertTrue(s.start(MusicState.CALM, calm, 40), "intro must be played");
        assertEquals(MusicState.CALM, s.playing());
        assertTrue(s.inIntro());
        assertEquals(40 + 104, s.nextTriggerTick());
        assertFalse(s.loopDue(143));
        assertTrue(s.loopDue(144));
        s.loopStarted();
        assertFalse(s.inIntro());
        assertEquals(40 + 522, s.nextTriggerTick());
    }

    @Test
    void moodChangeWaitsForTransitionPoint() {
        MusicSession s = new MusicSession();
        s.start(MusicState.CALM, calm, 0);
        s.request(MusicState.ALARM, Quantize.BAR, 30);
        assertEquals(MusicState.ALARM, s.pending());
        // calm transitions every 2 bars = 104.35 ticks
        assertEquals(104, s.switchTick());
        assertFalse(s.switchDue(103));
        assertTrue(s.switchDue(104));
    }

    @Test
    void beatQuantizeIsFaster() {
        MusicSession s = new MusicSession();
        s.start(MusicState.ALARM, alarm, 0);
        s.request(MusicState.NONE, Quantize.BEAT, 10);
        assertEquals(18, s.switchTick());
    }

    @Test
    void requestingCurrentMoodCancelsPendingSwitch() {
        MusicSession s = new MusicSession();
        s.start(MusicState.CALM, calm, 0);
        s.request(MusicState.ALARM, Quantize.BAR, 10);
        s.request(MusicState.CALM, Quantize.BAR, 20);
        assertNull(s.pending());
        assertFalse(s.switchDue(500));
    }

    @Test
    void newerRequestKeepsScheduledBoundary() {
        MusicSession s = new MusicSession();
        s.start(MusicState.CALM, calm, 0);
        s.request(MusicState.ALARM, Quantize.BAR, 10);
        long tick = s.switchTick();
        s.request(MusicState.NONE, Quantize.BAR, 20);
        assertEquals(MusicState.NONE, s.pending());
        assertEquals(tick, s.switchTick());
    }

    @Test
    void bundledStudioMetadataIsUsable() {
        ResourceSource classpath = ResourceSource.classpath(getClass().getClassLoader());
        assumeTrue(classpath.read(MusicLibrary.path(MusicState.CALM)).isPresent()
                && classpath.read(MusicLibrary.path(MusicState.ALARM)).isPresent(), "studio music not generated yet");
        MusicLibrary bundled = MusicLibrary.load(classpath, Logger.getAnonymousLogger());
        for (MusicState state : new MusicState[] {MusicState.CALM, MusicState.ALARM}) {
            MusicMetadata m = bundled.get(state).orElseThrow();
            assertTrue(m.loopSeconds() > 0 && m.bpm() > 0, state.id());
            assertEquals(m.barSeconds() * m.loopBars(), m.loopSeconds(), 0.01, "loop is a whole number of bars");
        }
    }

    @Test
    void stoppingProducesSilence() {
        MusicSession s = new MusicSession();
        s.start(MusicState.CALM, calm, 0);
        s.outroStarted(MusicState.CALM);
        assertEquals(MusicState.CALM, s.outro());
        assertFalse(s.start(MusicState.NONE, null, 200));
        assertNull(s.outro());
        assertEquals(MusicState.NONE, s.playing());
        assertFalse(s.loopDue(100_000));
    }

    @Test
    void metadataWithoutIntroStartsLoopDirectly() {
        MusicMetadata noIntro = MusicMetadataParser.parse("""
                {"state":"calm","bpm":120,"meter":[4,4],"loop":{"duration_s":8.0,"bars":4},"extra":{"x":1}}
                """);
        MusicSession s = new MusicSession();
        assertFalse(s.start(MusicState.CALM, noIntro, 7));
        assertTrue(s.loopDue(7));
        s.loopStarted();
        assertEquals(7 + 160, s.nextTriggerTick());
    }
}
