// Generate THIRD_PARTY_NOTICES.md from the packages actually bundled into runtime/dist.
//   node scripts/third-party.mjs          # write the file
//   node scripts/third-party.mjs --check  # fail if the file is out of date (CI)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const RT = path.join(ROOT, 'runtime');
const require = createRequire(path.join(RT, 'package.json'));
const { build } = require('esbuild');

const entries = ['studio-core', 'studio-texture', 'studio-model', 'studio-audio', 'studio-minecraft'].map((s) => `src/mcp/${s}.js`).concat(['src/dashboard/main.js', 'src/cli/studio.js']);
const r = await build({ absWorkingDir: RT, entryPoints: entries, bundle: true, platform: 'node', format: 'esm', write: false, metafile: true, outdir: 'tmp', splitting: true, logLevel: 'silent' });
const pkgs = new Set();
for (const f of Object.keys(r.metafile.inputs)) {
  const parts = f.split(/[\\/]/);
  const i = parts.lastIndexOf('node_modules');
  if (i < 0) continue;
  pkgs.add(parts[i + 1].startsWith('@') ? `${parts[i + 1]}/${parts[i + 2]}` : parts[i + 1]);
}
const rows = [...pkgs].sort().map((p) => {
  const dir = path.join(RT, 'node_modules', p);
  const pj = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));
  const lic = fs.readdirSync(dir).find((f) => /^licen[cs]e/i.test(f));
  return { name: p, version: pj.version, license: pj.license || 'UNKNOWN', repo: (pj.repository?.url || pj.repository || pj.homepage || '').toString().replace(/^git\+/, '').replace(/\.git$/, '').replace(/^git:\/\//, 'https://').replace(/^(?!https?:)([\w-]+\/[\w.-]+)$/, 'https://github.com/$1'), text: lic ? fs.readFileSync(path.join(dir, lic), 'utf8').trim() : null };
});
const bad = rows.filter((x) => !/^(MIT|ISC|BSD-2-Clause|BSD-3-Clause|Apache-2\.0|0BSD|BlueOak-1\.0\.0)$/.test(x.license));
let md = `# Third-party notices\n\nMinecraft Studio is MIT-licensed. The bundled runtime (\`runtime/dist\`) includes the following third-party packages. This file is generated by \`node scripts/third-party.mjs\`.\n\n| Package | Version | License |\n|---|---|---|\n`;
md += rows.map((x) => `| [${x.name}](${x.repo}) | ${x.version} | ${x.license} |`).join('\n');
md += `\n\n## External tools (not bundled)\n\nMinecraft Studio can *use* these when installed by the user. They are separate programs, run as separate processes, and are not redistributed:\n\n| Tool | License | Use |\n|---|---|---|\n| FFmpeg | LGPL-2.1+/GPL (build dependent) | audio conversion & processing |\n| eSpeak NG | GPL-3.0 | local draft TTS |\n| Blockbench | GPL-3.0 | optional live modelling (via a user-installed MCP plugin) |\n| sosadly/blockbench-mcp | MIT | optional Blockbench MCP bridge |\n| jasonjgardner/blockbench-mcp-plugin | GPL-3.0 | optional Blockbench MCP bridge |\n| github/github-mcp-server | MIT | optional GitHub integration |\n| PaperMC Paper / paper-api | GPL-3.0 (see PaperMC/Paper) | test server downloaded on demand; the demo compiles against paper-api with provided scope (not bundled) |\n\nNo code from these projects is copied into Minecraft Studio.\n\n## License texts\n`;
for (const x of rows) md += `\n### ${x.name} ${x.version}\n\n\`\`\`\n${x.text || `${x.license} (see ${x.repo})`}\n\`\`\`\n`;
const out = path.join(ROOT, 'THIRD_PARTY_NOTICES.md');
if (process.argv.includes('--check')) {
  const cur = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  if (cur !== md) { console.error('THIRD_PARTY_NOTICES.md is out of date: run node scripts/third-party.mjs'); process.exit(1); }
} else fs.writeFileSync(out, md);
if (bad.length) { console.error(`Non-permissive or unknown licenses: ${bad.map((b) => `${b.name} (${b.license})`).join(', ')}`); process.exit(1); }
console.log(rows.map((x) => `${x.name}@${x.version} ${x.license}`).join('\n'));
